version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./bbs-web-admin/dist:/usr/share/nginx/static/admin
      - ./bbs-web-pc/dist:/usr/share/nginx/static/pc
      - ./bbs-web-mobile/dist:/usr/share/nginx/static/mobile
      - ./log/nginx:/var/log/nginx
    depends_on:
      - mysql
    networks:
      - bbs-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "33066:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Q5EC6VV7Zs # 请根据需要修改密码
      MYSQL_DATABASE: bbs-pro  # 可选：创建默认数据库
    volumes:
      - mysql-data:/var/lib/mysql
      - ./bbs-pro.sql:/docker-entrypoint-initdb.d/bbs-pro.sql:ro
    networks:
      - bbs-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql-data:

networks:
  bbs-network:
    driver: bridge