version: '3.8'

services:

  mysql:
    image: 18yk3iuztwn8ax.xuanyuan.run/library/mysql
    container_name: mysql
    ports:
      - "33066:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # 请根据需要修改密码
      MYSQL_DATABASE: bbs-pro  # 可选：创建默认数据库
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bbs-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  mysql-data:

networks:
  bbs-network:
    driver: bridge